### ISSUE TITLE
the training input data, and way to generate FACE PROFILING

### ISSUE THREAD

**Issue by spark123456789** [cleardusk/3DDFA#1]
Deal Sir,
Thank you for sharing your code!

1.As I read your paper, the input data not only include the raw image, but also include the PNCC and PAC data, my Question is, Will you update the script to generate the PNCC and PAC data, If not, Can you give me some tips to generate them?
2. You also did some face profiling, Can you give me some tips on how to do that?

**Comment by cleardusk** [comment]
Thanks for your interest in my work.
1. I have released the cropped training images with augmentation. For the origin images , you can refer to this link http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm. The PNCC and PAC features are under development.
2. For face profiling, the link http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm provides the MATLAB source code.
