### ISSUE TITLE
How to generate cropped image?

### ISSUE THREAD

**Issue by ForestWang** [cleardusk/3DDFA#10]
Hi cleardusk:

    I found that the cropped image of AFLW are not resized to 120*120 directly from original image, so how to you generate them?

 thank you very much!

Forest

**Comment by cleardusk** [comment]
I added the face cropping part in [here](https://github.com/cleardusk/3DDFA/blob/master/benchmark/benchmarkCrop.m). Tks for your interest.

**Comment by ForestWang** [comment]
many thanks for your kindness.

**Comment by cleardusk** [comment]
The cropping code lies in main.py now.
