### ISSUE TITLE
The unit of coordinate

### ISSUE THREAD

**Issue by DuziKim** [cleardusk/3DDFA#100]
Hi. Thanks for your excellent work!

but i wonder about the 300W-LP data's coordinates' unit.

1. as i know, the world coordinate of 3D vertices is represented in millimeter or centimeter.
if i create a 3DMM vertices, are their coordinates are in unit of millimeter?

2. and how about 2D ground truth and projected 3D ground truth(pts_2d, pts_3d variables from mat files in ../300W_LP/landmarks/ directory.)? are they are in millimeters?

3. should i convert them into pixel unit to use them for regressing 2D keypoints?

I'm the very beginner of this field! thank you!

**Comment by cleardusk** [comment]
3DMM represents the 3D face in Pixel unit. As the projection is orthogonal, no physical unit is involved in this repo.

**Comment by DuziKim** [comment]
also z-coordinate? is this in Pixel unit?
