### ISSUE TITLE
How is this related to Anti-Spoofing?

### ISSUE THREAD

**Issue by congphase** [cleardusk/3DDFA#101]
@cleardusk I'm a noob, please help me with this question: How can I use this code to perform spoof face dataset synthesis as mentioned in your paper: https://arxiv.org/pdf/1901.00488v2.pdf

I've looked through the repo and see that the main features are Face alignment, Face reconstruction, 3D pose estimation, Depth image estimation and PNCC & PAF features; and also the code. I didn't know what part is for spoof face dataset synthesis. Please explain this to me.

**Comment by cleardusk** [comment]
Sorry for that, this repo is not for that paper [Improving Face Anti-Spoofing by 3D Virtual Synthesis](https://arxiv.org/abs/1901.00488). The code of that paper is not released.
