### ISSUE TITLE
how to generate the .mat of the training set

### ISSUE THREAD

**Issue by ReverseSystem001** [cleardusk/3DDFA#105]
thanks for sharing the codes, could you tell me how to generate the .mat file of the training set if it is convenient???

**Comment by ReverseSystem001** [comment]
Is the training GT(.mat) achieved based on BFM2009???

**Comment by cleardusk** [comment]
The generation part is not release as this part is a little messy. The generation is based on 300W-LP.

**Comment by ReverseSystem001** [comment]
you mean the Face Profiling matlab code from http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm is not generation code???? but The description information of the code is：The MATLAB code to synthesize large-pose face appearances with 3D Face Model.It's like the realization of the fourth part of the paper.

**Comment by ReverseSystem001** [comment]
i want to replace the BFM09 with 17, and then use the face3d script 8_generate_posmap_300WLP.py to generate uv map. you now. i need change the training set GT which should be generated based on BFM2017. is there some way to achieve this???
