### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by Gnabe** [cleardusk/3DDFA#106]
Hello,

did you test the 2D performance on 300W? Also, is the reported result on AFLW2000-3D the 2D error as the code suggests or the 3D error?

**Comment by cleardusk** [comment]
300W is not tested.
3D error is not the same as 2D error. For 3D error, the z-axis must perform the translation. PRNet does this.

**Comment by Gnabe** [comment]
Thanks for the response. 
Is this model only trained to produce low 2D error? Why do you even guess the z-translation in that case? Is the result in the paper of 3.8 % on AFLW2000-3D also  the 2D error?
