### ISSUE TITLE
cascade regression

### ISSUE THREAD

**Issue by KirtoXX** [cleardusk/3DDFA#108]
Hi,do u have plan to release cascade regression edition？

**Comment by cleardusk** [comment]
Cascade structure does not benefit the performance in our setting, thus is not released.

**Comment by AaboutL** [comment]
In which setting, can cascade structure benefit the performance?

**Comment by cleardusk** [comment]
For feature map regression, cascade structure may help, e.g. PRNet or other position map regression-based methods.
