### ISSUE TITLE
Doubt about the AFLW_GT_pts68

### ISSUE THREAD

**Issue by liuppboy** [cleardusk/3DDFA#109]
Hi cleardusk,

From your paper, AFLW dataset only have 21 key points annotations. However, in this repo, I find that there is [ALFW_GT_pts68](https://github.com/cleardusk/3DDFA/blob/master/test.configs/AFLW_GT_pts68.npy). I am just wondering how do you obtain the AFLW_GT_pts68 and whether its annotation is reliable. Because after visualization, I find that some annotations are not accurate. 

Thanks!

**Comment by ReverseSystem001** [comment]
DO YOU KNOW WHY NOW?

**Comment by cleardusk** [comment]
From the dataset 300W-LP.
