### ISSUE TITLE
Another 3DMM

### ISSUE THREAD

**Issue by BouOus** [cleardusk/3DDFA#11]
Dear Sir,

Thank you for this amazing work !

My question is : 
If we have another 3DMM how can we re make the work to create antoher 300W Dataset with the new 3DMM parameters ? which steps should we take ?

Thank you.

**Comment by cleardusk** [comment]
You can ref [here](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm)
