### ISSUE TITLE
hi, where can i find the model_refine.mat?

### ISSUE THREAD

**Issue by ReverseSystem001** [cleardusk/3DDFA#111]
hi, thanks for sharing the codes. when i read the code under 3DDFA/BFM_Remove_Neck/.  
the Attention says: the z-axis value of bfm.ply and bfm_refine.ply file are opposed in model_refine.mat, do not use these two ply file in training. 
but, where can i find the model_refine.mat file???

**Comment by ReverseSystem001** [comment]
thanks. i have find it.

**Comment by CodingMice** [comment]
> thanks. i have find it.

where is the model_refine.mat
