### ISSUE TITLE
Curious about when will you share the face anti-spoofing by 3D virtual synthesis project?

### ISSUE THREAD

**Issue by BruceDai003** [cleardusk/3DDFA#116]
This repo is awesome, as I was learning about face anti-spoofing. I noticed that you have published the paper "Improving Face Anti-Spoofing by 3D Virtual Synthesis", which seems quite promising. I am looking forward to see it, so I'm just curious about when will you share it please?

**Comment by cleardusk** [comment]
Sorry for that, the code releasing of the paper [Improving Face Anti-Spoofing by 3D Virtual Synthesis](https://arxiv.org/abs/1901.00488) is not on my schedule. But welcome to contact me for discussion.
