### ISSUE TITLE
Facewarehouse expression

### ISSUE THREAD

**Issue by zhaishengfu** [cleardusk/3DDFA#117]
wonderful project! I am amazed about the result. Thanks for your work.
I have a question. In the original paper, the expression is 29 dimention used facewarehouse, but I think your project just used BFM 10 dimension expression, right? so some facial expression can not be reconstructed such as left mouth up. Do you think use facewarehouse will improve the result?

**Comment by cleardusk** [comment]
You can give it a try. Besides, you can also try a 29-dimension version of expression parameters.
