### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ReverseSystem001** [cleardusk/3DDFA#119]
cd utils/cython
python3 setup.py build_ext -i
and then the files like mesh_core_cython.*.so generated.

when i run : python3 main.py -f samples/test1.jpg 
it shows error: Segmentation fault (core dumped), is this the problem of my cython version?
hope your replay! thanks

**Comment by cleardusk** [comment]
There is no enough information to diagnose.

**Comment by ReverseSystem001** [comment]
The problem has been solved because of the pytorch version. thanks for your response
