### ISSUE TITLE
Rendered mesh

### ISSUE THREAD

**Issue by joaootavio93** [cleardusk/3DDFA#12]
Can you explain how the .mat files generated by visualize.py code are represented? I noticed that the meshes are 3x53215. I tried to plot those meshes in MATLAB but I didn't see face models.

**Comment by cleardusk** [comment]
You can use the `trisurf` function to render the 3D face mesh. You may need the triangle index from BFM model.

**Comment by solashirai** [comment]
How exactly should we go about getting the triangle indexes?
Would you happen to have any code that you can share to show the exact functions for rendering the 3D face meshes?
