### ISSUE TITLE
How to make the eyes closed?

### ISSUE THREAD

**Issue by fiona-lxd** [cleardusk/3DDFA#121]
Hi, thank you for your contribute. I'm curios that how to make the eyes moved. I found that once the vertices change, the expression of the face gets changed too. But the eyes never changes. Do you know how to make eyes moved?

**Comment by tommy19970714** [comment]
I am interested in this question. I would also like to try the same thing.
I tried some images including people who have closed eyes using latest pre-trained model, but it did not recognize closed eyes.
According to the README, the developer mentions that the recognition of eyes depends on the parameters clipping in training.
There are parameters in the following code. https://github.com/cleardusk/3DDFA/blob/master/utils/params.py
Which parameters should we change?

**Comment by cleardusk** [comment]
Honestly, due to the distribution of 300W-LP where closed-eyes images are scarce, the model trained on 300W-LP hardly gives the closed-eye results, no matter how many dimensions you clip.
If you want to make eyes closed, go to collect closed-eye faces, fit them and train on the collected or combined dataset.

**Comment by tfygg** [comment]
> Honestly, due to the distribution of 300W-LP where closed-eyes images are scarce, the model trained on 300W-LP hardly gives the closed-eye results, no matter how many dimensions you clip.
> If you want to make eyes closed, go to collect closed-eye faces, fit them and train on the collected or combined dataset.

Thank you for your contribute! 

I want to know a few questions: 
- how much data is needed?
- what is the percentage of  closed eyes face data?

**Comment by ywlife** [comment]
Maybe you can refer to FRDA(https://github.com/Star-Clouds/FRDA)

**Comment by cleardusk** [comment]
@ywlife  FRDA gives an output example of closed eyes, what training data do you use?
