### ISSUE TITLE
Could you please provide whole w_shp and w_exp file?

### ISSUE THREAD

**Issue by baicwang** [cleardusk/3DDFA#122]
You mentioned that original shape of 3DMM basis is 159645x199 in https://github.com/cleardusk/3DDFA/issues/83.
Could you please  provide the whole w_shp and w_exp file?

**Comment by WinnieLaugh** [comment]
Hi, I am also looking for the answer to this issue. 

Could you please provide the code to generate the .npy file ourselves? So that we can train the model on the basis of 159645x60 or 159645x199. @cleardusk Thanks in advance!

**Comment by cleardusk** [comment]
The release is on the schedule, but maybe on another project, the related work is under review.
