### ISSUE TITLE
some questions about deepinsight/insightface

### ISSUE THREAD

**Issue by ReverseSystem001** [cleardusk/3DDFA#125]
when i read the problems of insightface, i find the link you attached.
The tsv files of raw images.
link
https://msceleb.blob.core.windows.net/ms-celeb-v1-split/MsCelebV1-ImageThumbnails.part.00.tsv
Do you have the raw images now   and does the cleanlist useful???
hope your replay!!!

**Comment by cleardusk** [comment]
Sorry, I havent.
