### ISSUE TITLE
Is training phase different from the setting in original paper?

### ISSUE THREAD

**Issue by chenjianyi** [cleardusk/3DDFA#126]
1. Simplified version of shape (40d) and expression (10) model is used. 
2. Cascaded Regression is not used.
3. PAF and PNCC are not feedback into network. The network(MobileNetV1) maps input image to params directly.
4. Network architecture is replaced by MobileNetV1，and there is just one stream exists.

Is my understanding right?
But 2 and 3 may improve the performance, I just guess.

Thank you for your work and hope for your kind reply!

**Comment by cleardusk** [comment]
Under the setting of this repo / this improved version, the benefits of 2 and 3 can be ignorable.

**Comment by Ivy147** [comment]
> Under the setting of this repo / this improved version, the benefits of 2 and 3 can be ignorable.

So can you tell me what is the most important thing to get such a good performance?
