### ISSUE TITLE
How to fit the extracted face features in a full head mesh?

### ISSUE THREAD

**Issue by AIdeveloper-oz** [cleardusk/3DDFA#129]
Hi, Thanks for sharing this awesome work. I wanted to make a full face 3D model, in which I can later fit some hair features. Also can this output mesh be attached to a separate 3D mesh? 
Thanks in advance!.

**Comment by cleardusk** [comment]
FaceProfilling does it by fitting anchor points on face mesh to full head, you may give it a try.

**Comment by AIdeveloper-oz** [comment]
Great, Thanks for the reply. I found a link for the face profiling matlab code in the repository, but its unavailable. Suggest any alternate sources even if available in python?

**Comment by cleardusk** [comment]
As far as I know, there is no public python repo. I re-upload the Matlab version here: [FaceProfiling](https://drive.google.com/open?id=1f4686yak4lGHLD6MfIiX5knVtq8a762d).

**Comment by AIdeveloper-oz** [comment]
Thanks for sharing. I will start proceeding with this.

**Comment by AIdeveloper-oz** [comment]
Hi, I dont have much knowledge on Matlab and just started with it. Can the matlab based face profiling integrated along with the existing project? The end output must be the merging of the frontal face mesh from 3DDFA on the full head mesh. Please help me to solve this. Thanks

**Comment by cleardusk** [comment]
3DDFA only outputs the 3DMM parameters of  face mesh. If combined with the head mesh, you should fit it or use a full-head face model.

**Comment by lyyiangang** [comment]
> Hi, I dont have much knowledge on Matlab and just started with it. Can the matlab based face profiling integrated along with the existing project? The end output must be the merging of the frontal face mesh from 3DDFA on the full head mesh. Please help me to solve this. Thanks

you can refer to this [link](https://github.com/TimoBolkart/BFM_to_FLAME/blob/ac58beffe73b335a764949cc8398b7c9d580f9ff/mesh_convert.py#L0-L1), this script can fit bfm face model to flame head model. I think this is what you want.
