### ISSUE TITLE
How exactly should we go about getting the triangle indexes?

### ISSUE THREAD

**Issue by solashirai** [cleardusk/3DDFA#13]
Would you happen to have any code that you can share to show the exact functions for rendering the 3D face meshes?

_Originally posted by @solashirai in https://github.com/cleardusk/3DDFA/issues/12#issuecomment-426053146_

**Comment by solashirai** [comment]
I was able to figure it out.
For any other wayward souls that are looking for how to do it: I used the 3DDFA code from http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm as well as the BaseFaceModel from https://faces.dmi.unibas.ch/bfm/index.php?nav=1-1-0&id=details
the 3DDFA code from the first link contains matlab code for generating face meshes, and you can plug in the vertex info (generated by visualize.py in this repo)

**Comment by cleardusk** [comment]
I have converted part of BFM model to `npy` format in directory `train.configs` in this repo. Once 3d face mesh generated, the matlab function `trisurf` can be called to render it.

**Comment by cleardusk** [comment]
Thanks @solashirai for providing more specific information.
