### ISSUE TITLE
Yaw,Pitch,Roll

### ISSUE THREAD

**Issue by Alpang54** [cleardusk/3DDFA#131]
Hello, I noticed that in line 160 of main.py, the values of the yaw,pitch roll can be obtained
`P, pose = parse_pose(param)  # Camera matrix (without scale), and pose (yaw, pitch, roll, to verify)`

However, when I attempted to print the results of pose using the sample image of test1 ( as in the readme), the values obtained were (-0.2982479758550047, 0.16620569715835162, 0.28968614317706604), which looked too small to be correct seeing that the face is tilted quite a bit. (From the resulting pose image as well) Can I check if this is correct?

**Comment by cleardusk** [comment]
Radian to degree converting? For example: pitch * 180 / pi

**Comment by Alpang54** [comment]
Oh, thanks. I'd just assumed it was in degrees, didnt think about that.

**Comment by g2ragrawal** [comment]
i tried this but this takes more time. i want real time pose estimation without gpu.Does anybody know better method?
