### ISSUE TITLE
Actual depth

### ISSUE THREAD

**Issue by Alpang54** [cleardusk/3DDFA#134]
Good day, I've looked through the code and managed to find the method "cgets_depths_image" from utils.render.py

```
def cget_depths_image(img, vertices_lst, tri):
    """cython version for depth image render"""
    h, w = img.shape[:2]
    c = 1

    depths_img = np.zeros((h, w, c))
    for i in range(len(vertices_lst)):
        vertices = vertices_lst[i]

        z = vertices[2, :]
        z_min, z_max = min(z), max(z)
        vertices[2, :] = (z - z_min) / (z_max - z_min)
        z = vertices[2:, :]

        depth_img = crender_colors(vertices.T, tri.T, z.T, h, w, 1)
        depths_img[depth_img > 0] = depth_img[depth_img > 0]

    depths_img = depths_img.squeeze() * 255
    return depths_img
```
Can I check with you how would i get the actual depth from this? I assume that the depth has been normalized since the range is from [0-1], but i can't figure out how to reverse engineer the actual depth

**Comment by cleardusk** [comment]
What the actual depth means? Not normalizing it is what you want?

**Comment by Alpang54** [comment]
Yes, I'd like to know the estimated depth of the person. I.e in metres/cm etc.
I assume that the line `vertices[2, :] = (z - z_min) / (z_max - z_min)` is the one responsible for the normalization, but I'm not sure what the values represent when no normalization is done.
The aim of what I'm trying to do is to obtain the 3D position of the face in the image (x,y,z), and would appreciate any help that you are able to provide

**Comment by Alpang54** [comment]
Update:
`def P2sRt(P):
    ''' decompositing camera matrix P.
    Args:
        P: (3, 4). Affine Camera Matrix.
    Returns:
        s: scale factor.
        R: (3, 3). rotation matrix.
        t2d: (2,). 2d translation.
    '''
    t3d = P[:, 3]
    R1 = P[0:1, :3]
    R2 = P[1:2, :3]
    s = (np.linalg.norm(R1) + np.linalg.norm(R2)) / 2.0
    r1 = R1 / np.linalg.norm(R1)
    r2 = R2 / np.linalg.norm(R2)
    r3 = np.cross(r1, r2)

    R = np.concatenate((r1, r2, r3), 0)
    return s, R, t3d`

I believe this method returns what Im asking for (3D position) from t3d. If possible, i'd like to know if im correct before closing this
