### ISSUE TITLE
Cython Build Issue

### ISSUE THREAD

**Issue by AIdeveloper-oz** [cleardusk/3DDFA#135]
Hi, I am trying to run this project in Anaconda environment. When I build the cython part, I get the following error **C:\3dhead\3DDFA-master\utils\cython>python setup.py build_ext -i
running build_ext
skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
building 'mesh_core_cython' extension
error: Unable to find vcvarsall.bat**
Please help me to clear the issue. Thanks

**Comment by cleardusk** [comment]
Sorry for that I have no Windows environment for testing.

**Comment by cleardusk** [comment]
Close as there are no further replies.
