### ISSUE TITLE
Is it possible to use two images(side poses) to construct similar mesh?

### ISSUE THREAD

**Issue by AIdeveloper-oz** [cleardusk/3DDFA#136]
Hi, your work has made me to explore more in 3D reconstruction. Thanks for this. 

- I am looking to make a model with 270 degree view with the hair/head. I've planned to use two side posed images for the reconstruction. Please guide me in which part do I need to rework and correct me if my path towards the objective is wrong. 

- Secondly, when I import the result obj in any designing software(Unity, Maya), the obj doesn't fit in the origin, every time it loads into different positions. What would be the reason for this?

**Comment by cleardusk** [comment]
Multi-view or two-viewre reconstruction in your need may need to refer to more related papers, 3DDFA is originally designed for single-view reconstruction.
The reconstruction vertices are under pixel coordinates, which maybe inconsistent with Unity or Maya. I did not test the reconstruction results in these designing softwares, and may [this issue](https://github.com/cleardusk/3DDFA/issues/138) helps?

**Comment by cleardusk** [comment]
Close as there are no further discussions.
