### ISSUE TITLE
Pose Information

### ISSUE THREAD

**Issue by joaootavio93** [cleardusk/3DDFA#14]
How to take the estimated pose information from the python code? I noticed that some generated .mat files inside the 300W-3D folder has the Pose_Param variable, which contains the pose information. But the .mat files generated by the visualize.py code do not provide this information.

**Comment by cleardusk** [comment]
Different from the paper which fitted 6 degrees of freedom with one scale param, my implementation is to regress the matrix param containing 12 (=3x4) params. If you want to extract the pose param not in matrix form, you can convert the matrix to angle like [here](https://pdfs.semanticscholar.org/6681/37fa4b875d890f446e689eea1e334bcf6bf6.pdf).
