### ISSUE TITLE
Are there plans on outputting a file formatted for import in 3D applications?

### ISSUE THREAD

**Issue by delebash** [cleardusk/3DDFA#151]
This is a very nice program.  I can't tell from the file produced but I believe you are producing x,y,z for facial coordinates.  If this is the case it would be nice to be able to import the motion capture data into 3D programs such as Blender,Maya,Unity etc.  A standard format for importing is .[fbx ](https://en.wikipedia.org/wiki/FBX)which is preferable. Alternatively you have .[bvh](https://en.wikipedia.org/wiki/Biovision_Hierarchy).

Thanks for the consideration!
Dan

**Comment by cleardusk** [comment]
A good request. But I can not implement it now due to my limited time, and welcome for any contributions : )

**Comment by delebash** [comment]
Thanks!
