### ISSUE TITLE
how to prepare augmented training dataset

### ISSUE THREAD

**Issue by ForestWang** [cleardusk/3DDFA#16]
Dear Sir:

    Currently, the training data and benchmark data sets are cropped based on labeled facial landmarks.
During inference, if we don't have landmarks, need face bounding box to crop the face. so in order to do the same preprocess both training and inference, need to regenerate training data according to face detection result. so is it possible to share current training data generation scripts.

 thank you very much.

**Comment by cleardusk** [comment]
This is in the future plan. I am very busy these days so the data-preprocess code release may be delayed. Welcome to keep watching on this repo.

**Comment by KangolHsu** [comment]
in dataset 300W-LP，the pose has 7 param below ：
%% Pose Parameter
phi = Pose_Para(1); % pitch
gamma = Pose_Para(2); % yaw
theta = Pose_Para(3); % roll
t3dx = Pose_Para(4); % translation
t3dy = Pose_Para(5);
t3dz = Pose_Para(6);
f = Pose_Para(7); % scale

In you code there is also a scale factor
def P2sRt(P):
    ''' decompositing camera matrix P.
    Args:
        P: (3, 4). Affine Camera Matrix.
    Returns:
        s: scale factor.
        R: (3, 3). rotation matrix.
        t2d: (2,). 2d translation.
    '''


My question is : what's the difference between this two scale factor ?

**Comment by ZHJNCUT** [comment]
> 在数据集300W-LP中，姿势有以下7个参数： %% Pose Parameter phi = Pose_Para(1); % 俯仰 伽玛 = Pose_Para(2); % 偏航 θ = Pose_Para(3); % 滚动 t3dx = Pose_Para(4); % 平移 t3dy = Pose_Para(5); t3dz = Pose_Para(6); f = Pose_Para(7); ％ 规模
> 
> 在您的代码中还有一个比例因子 def P2sRt(P): ''' 分解相机矩阵 P。 参数： P: (3, 4)。仿射相机矩阵。 返回： s：比例因子。 罗：(3, 3)。旋转矩阵。 t2d：（2，）。二维翻译。 '''
> 
> 我的问题是：这两个比例因子有什么区别？

Have you solved it yet?
