### ISSUE TITLE
Landmark labels in dataset

### ISSUE THREAD

**Issue by kushwahashivam** [cleardusk/3DDFA#162]
I was trying to use the dataset provided over Google Drive. But I can not find any file that gives me landmarks of cropped images. These are the files in train.configs

['keypoints_sim.npy',
 'param_whitening.pkl',
 'u_exp.npy',
 'u_shp.npy',
 'param_all_norm.pkl',
 'param_all_norm_val.pkl',
 'train_aug_120x120.list.train',
 'train_aug_120x120.list.val',
 'w_exp_sim.npy',
 'w_shp_sim.npy']

Is there any way to get those landmarks for training?

**Comment by cleardusk** [comment]
The landmarks are reconstructed online, https://github.com/cleardusk/3DDFA/blob/master/utils/ddfa.py#L27.

**Comment by kushwahashivam** [comment]
Yeah, I got the solution.
