### ISSUE TITLE
Reasons for simplification of shape and expression parameters.

### ISSUE THREAD

**Issue by chengfeng0113** [cleardusk/3DDFA#169]
What are the reasons for the simplification of the number of shape parameters from 199 to 40 and the number of expression parameters from 29 to 10? To train smaller models? In fact, I found that the number of simplified expression parameters has a great impact on the accuracy of 3D key point location, but the simplified shape parameters have little effect. I think we need to do batch testing to find the best simplified parameters for shape and expression.

**Comment by cleardusk** [comment]
I agree with you. The expression parameters should not be eliminated too heavily. 60+20 or 60+29 is fine.

**Comment by chengfeng0113** [comment]
I will do some tests in this regard, thank you！

**Comment by ZHJNCUT** [comment]
> 我会做一些这方面的测试，谢谢！

How did you verify it and what conclusions did you draw?
