### ISSUE TITLE
预训练模型测试

### ISSUE THREAD

**Issue by Zhaohouqiang0220** [cleardusk/3DDFA#173]
github上的预训练模型测试结果为什么与论文中的结果不一致？

**Comment by cleardusk** [comment]
这个是 improved version，速度快了很多，性能稍微若一些

**Comment by Zhaohouqiang0220** [comment]
这套训练代码就是improved version吗？ 训练出的模型就是速度快，性能稍微弱一些？

**Comment by cleardusk** [comment]
You can go through the repo to draw your conclusion.
