### ISSUE TITLE
About the offset parameter

### ISSUE THREAD

**Issue by chengfeng0113** [cleardusk/3DDFA#175]
I found that during training, the z-axis parameter in the offset parameter is not necessary, if only to get the 3D key points after projection. And for the training of 2D images, this parameter may affect the training effect. Have you done any related experiments?

**Comment by cleardusk** [comment]
I made z equal to gt, in other words, z does not contribute to any gradients. The effect can be ignored in 3d dense face alignment tasks in previous exps.

**Comment by chengfeng0113** [comment]
I see, thank you!
