### ISSUE TITLE
关于计算姿态问题

### ISSUE THREAD

**Issue by weilenggmj** [cleardusk/3DDFA#177]
请问此代码中那一部分是在计算人脸姿态的？可以大致描述一下吗？
谢谢

**Comment by cleardusk** [comment]
You can refer to: https://github.com/cleardusk/3DDFA_V2/blob/master/utils/pose.py

**Comment by weilenggmj** [comment]
感谢您的回答。我还想知道训练程序是怎样使用他的呢？训练程序中计算姿态吗？

**Comment by cleardusk** [comment]
根据输出的参数计算的 pose，细节请参考代码。

**Comment by weilenggmj** [comment]
您好我还想问一些问题，我刚接触这个领域，想弄清楚训练代码的一些问题，
1. 我不太确定3DDFA中train.py训练的是什么，是训练3DMM的参数的吗？
2. 姿态是仅在运行main.py计算的吗？（因为我在train.py没有用到pose.py中的函数）
3. 位姿的参数是parse_pose中的P,Pose吗？
4. 3DMM模型在哪一部分体现？
问题可能比较不专业请见谅。

**Comment by xuanzhang2021** [comment]
当前3DDFA这个代码包中有计算pose的吗？可否有计算低头，转头这些角度的？
