### ISSUE TITLE
eyes landmark do not blink

### ISSUE THREAD

**Issue by jesszgc** [cleardusk/3DDFA#18]
hello author,
   i tried your code for 3d face landmark in live camera, using mtcnn for face detection work and your face crop method. and i find the eyes landmark do not blink (i am blinking). 
  is this correct?

**Comment by cleardusk** [comment]
The training data has **few** faces closing eyes, so the model may perform badly for blink eyes : (

**Comment by jesszgc** [comment]
thanks a lot,
      the face rect is a problem. using mtcnn's face detection result to crop the image cannot get an accurate landmark(mostly a little higher than the real location ).
 for live test, we can not crop the img base on unknowed landmarks, if we retrain the net with facedetector's(like mtcnn, haar, LBP,HOG) cropping images, will we get a better result?
