### ISSUE TITLE
About output

### ISSUE THREAD

**Issue by darchonyzx** [cleardusk/3DDFA#19]
Hello
I am A raw recruit about Face Alignment. Well, I see the output is 62 dimension of the mobilenet-1 model in the code, and I notice this is the first stage pre-train model.I guess I miss some crucial points. But what I want to know is that if I want to estimate the angle of a face image using this model, what should I focused on?
Thank you!

**Comment by cleardusk** [comment]
Thanks for your interest. You can refer to `matrix2angle` function [here](https://github.com/YadiraF/face3d/blob/89db034626d3e125d0b7a8f0d69b6f87c44cf076/face3d/mesh_numpy/transform.py#L333) to parse the angle.

**Comment by darchonyzx** [comment]
Thanks

**Comment by darchonyzx** [comment]
I notice the pose param 3x4 matrix form, the last column is the offset, but I still don't know how to calculate the pitch, yaw and roll. I test it with Multiple cropped faces, but there is deviation. I don't understand what the 3x4 matrix stands for.

**Comment by darchonyzx** [comment]
Thanks, I use mean and std in param_whitening.pkl to norm the matrix, then I use some labeled face images to test, and there is large deviation. So, is there any way to make the angle estimation of the outside of training dataset face images more accurate.

**Comment by cleardusk** [comment]
Did you follow the crop pipeline in [here](https://github.com/cleardusk/3DDFA/blob/master/benchmark/benchmarkCrop.m), it needs 68 landmarks to calculate the bounding box. Besides, mean and std in param_whitening.pkl is used to de-norm the predicted param matrix.
As I can not provide more details from your short description, you are recommended to add more detailed description here or send me an email with more specific information. In addition, any useful PR is welcomed.
