### ISSUE TITLE
Landmarks location on face / map of landmarks

### ISSUE THREAD

**Issue by leolellisr** [cleardusk/3DDFA#194]
Congratulations on your great work and thanks for sharing it.

Is there any reference to the location of the landmarks on face (or a map of the landmarks) generated with _dense_flag = **True**_ (the estimated 38k points)? 
Something like dlib in this image? <https://pyimagesearch.com/wp-content/uploads/2017/04/facial_landmarks_68markup.jpg>

When _dense_flag = **False**_, the location of the points is the same as the dlib, right?

I appreciate the attention.

**Comment by cleardusk** [comment]
The semantic positions are the same.

**Comment by cleardusk** [comment]
See https://github.com/anilbas/BFMLandmarks

**Comment by Bornblack** [comment]
annotation from https://github.com/anilbas/BFMLandmarks
![image](https://user-images.githubusercontent.com/49244832/145963754-146c29ed-8deb-4f05-a91d-81dda69425bb.png)
annotation from 3DDFA
![image](https://user-images.githubusercontent.com/49244832/145963479-8b6adb45-88c0-4fbc-a7aa-f008b997dc3c.png)

I find that the annotations are slightly different, especially the points around the eyebow , nose tip and nose-lip junction.
