### ISSUE TITLE
Regressor from 3D dense vertices to 3D keypoints

### ISSUE THREAD

**Issue by FishWoWater** [cleardusk/3DDFA#197]
Hi! Thanks for your nice work!

I am wondering how to obtain the indices of 68 keypoints from original 5w+ vertices

I want to get the indices of 106 keypoints, is there any solution? 

Thanks!

**Comment by cleardusk** [comment]
You may annotate it by yourself.

**Comment by FishWoWater** [comment]
@cleardusk Is there any tool I can make use of? (e.g. for visualization?)

**Comment by cleardusk** [comment]
meshlab

**Comment by FishWoWater** [comment]
@cleardusk OK Thanks

**Comment by FishWoWater** [comment]
@cleardusk  
Hi! I have another question:

**Comment by FishWoWater** [comment]
If I want to re-train  3DDFA with 128x128 inputs. I need to 
1. resize input images to 128 x 128 
2. decompose `f` from 3x4 camera parameters ( by pow(np.linalg.det(cam[:, :3]), 1/3) ) 
3. decompose offset from camera matrix 
4. let `f'` = `f * 128 / 128` and t_x = t_x + 4; t_y = t_y + 4; 

right?

**Comment by FishWoWater** [comment]
> If I want to re-train 3DDFA with 128x128 inputs. I need to
> 
> 1. resize input images to 128 x 128
> 2. decompose `f` from 3x4 camera parameters ( by pow(np.linalg.det(cam[:, :3]), 1/3) )
> 3. decompose offset from camera matrix
> 4. let `f'` = `f * 128 / 120` and `t_x = t_x + 4; t_y = t_y + 4`;
> 
> right?

I visualized the images in 120x120 and their 128x128 counterparts and I believe it's ok

**Comment by FishWoWater** [comment]
__
