### ISSUE TITLE
How to remove neck part 

### ISSUE THREAD

**Issue by wuneng** [cleardusk/3DDFA#2]
Hi,cleardusk
    Thank you for sharing your code!
    The 3d face shape often contains the neck part. How to remove it? Thanks in advance.

**Comment by cleardusk** [comment]
You can remove related indices and vertexes of the neck. But does it matters? The area of the neck part seems small.

**Comment by wuneng** [comment]
In some case, the neck part would be useless. Could you tell me the indices of neck part?

**Comment by cleardusk** [comment]
@wuneng You can use [MeshLab](http://www.meshlab.net/) to select neck indices, or delete the neck part then calculate the neck indices.

**Comment by wuneng** [comment]
Thanks, i will try.

**Comment by ZHJNCUT** [comment]
> 部部分

Can you tell me the correlation index of the neck?

**Comment by ZHJNCUT** [comment]
> 谢谢，我会尝试的。



> 谢谢，我会尝试的。

Can you tell me the correlation index of the neck?
