### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by liz6688** [cleardusk/3DDFA#21]
In the requested environment, I trapped into the problem 'Segmentation fault (core dumped'.
Do you konw the reason?

**Comment by cleardusk** [comment]
Please provide more information as I can not draw the conclusion from your current description.

**Comment by liz6688** [comment]
Actually, I don't have more information. I configured the required environment, then run 'python3 main.py -f samples/test1.jpg',  and encountered this problem.  
My environment: Python 3.6.7; [GCC 7.3.0] on linux; pytorch0.4.1; cv2 version 3.4.2. I am trying to find 'core.XXXX' file to get more information. Hope you have more suggestions.

**Comment by cleardusk** [comment]
Did you install Dlib module? `main.py` needs Dlib by default.

**Comment by liz6688** [comment]
Yes, I installed dlib with version 19.16.0.  
After trying 'gdb core-file core', it shown that Core  was generated by `python3 main.py -f samples/test1.jpg'.Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f447705f7c9 in ??
I don't know what I can do now.

**Comment by cleardusk** [comment]
Could you debug `main.py` in your environment? As I can not reproduce your situation.

**Comment by cleardusk** [comment]
On Linux (Ubuntu for example), dlib 19.16 version may cause conflicts with pytorch. In MacOS, everything is fine.
Therefore I recommend using dlib 19.5. 
`sudo pip3 install dlib==19.5.0`

**Comment by liz6688** [comment]
ok. I am trying to install dlib 19.5.0. thank u

**Comment by liz6688** [comment]
hi,


终于配置好了环境，直接pip3 install dlib==19.5.0 没有权限，最后下载了19.5.0的压缩包，从源码安装的dlib，下载了py36对应的opencv包，安装了opencv，跑出了main.py的结果，接下来找个数据集测试一下看看。
这次安装dlib，opencv终于长记性了，一定得版本对应，安装过程中y/n，不能只yes了。


谢谢





At 2018-11-14 20:51:44, "Jianzhu Guo" <notifications@github.com> wrote:


On Linux (Ubuntu for example), dlib 19.16 version may cause conflicts with pytorch. In MacOS, everything is fine.
Therefore I recommend using dlib 19.5.
sudo pip3 install dlib==19.5.0

**Comment by ivanhc** [comment]
Hi, 

I found some problem in MacOs X installing dlib using the "pip3 install dlib==19.5.0" to find the boost library.
 (Boost 1.68 and boost-python were installed using "brew install boost" and "brew install boost-python")

However, installing "pip3 install dlib" (the last dlib version), it was installed without any problem and the sample is working perfectly. 

Ivan
