### ISSUE TITLE
Can you share the 2D landmark for train_aug_120x120?

### ISSUE THREAD

**Issue by lishang6257** [cleardusk/3DDFA#210]
Thanks for your amzing work! Can you share the 2D landmarks for these augumented face images or share the code for agumenting face image from 300W-LP? Thanks very much and hope for your reply!

**Comment by Hamidoullah** [comment]
I have a serious problem to install torch.

**Comment by Hamidoullah** [comment]
Thanks you

**Comment by lishang6257** [comment]
> I have a serious problem to install torch.
The author of 3DDFA has given a detailed ‘Readme’ to run the code, you can try again.
