### ISSUE TITLE
skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)

### ISSUE THREAD

**Issue by 453875726** [cleardusk/3DDFA#211]
您好，我使用的是ubuntu18系统，
python3 setup.py build_ext -i前的步骤都正常进行
这一步没有运行错误，但是显示
skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
结果这一步骤进行后，cython文件夹没有新的文件，请问如何解决，谢谢！

**Comment by Lego514** [comment]
Hi there, did you clear the problem? I have the same error on google colab. @453875726

**Comment by Masterzhuior** [comment]
> 您好，我使用的是ubuntu18系统， python3 setup.py build_ext -i前的步骤都正常进行 这一步没有运行错误，但是显示 skipping 'mesh_core_cython.cpp' Cython extension (up-to-date) 结果这一步骤进行后，cython文件夹没有新的文件，请问如何解决，谢谢！

你好请问你解决这个问题了吗

**Comment by 453875726** [comment]
这个好像跑不通，所以后面我去用3ddfa2了
