### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by ileniTudor** [cleardusk/3DDFA#22]
hello, thank you for this work. Is there a way to publish the remove neck version of BFM data also on google drive? Is quite hard for me to download them from pan.baidu.

Thank you

**Comment by cleardusk** [comment]
Ok, I have updated the google drive download link [here](https://drive.google.com/file/d/1yi03Uq3j_GruOQGAfDi9_VzfYnALojrp/view?usp=drive_open).  If you are interested, please star it : )

**Comment by cleardusk** [comment]
Due to the license in [bfm2017](https://faces.dmi.unibas.ch/bfm/bfm2017.html), I will delete the no-neck version of BFM data soon.
