### ISSUE TITLE
The rendering result from the render_demo.m and the meshlab

### ISSUE THREAD

**Issue by SunnyDp** [cleardusk/3DDFA#28]
First, Thanks to your great job for 3D face alignment. Here I got a problem about the visual 3D face rendering results. For example, I run the render_demo.m under the folder ‘visualize’ , and the ‘test1_0.mat’ and 'test1_1.mat' are created by running the command 'python3 main.py -f samples/test1.jpg', the rendering result is about x-axis mirror symmetry with the result provided in the ‘test1_0.jpg’ and 'test1_1.jpg', which means the face is inverted. And I get the correct result by replace the command ‘vertex = load('test1_0');‘ with ’vertex = load('image00427');‘ which used the ’image00427.mat‘ you provided. Why I got this problem? I look forward to your reply.

**Comment by cleardusk** [comment]
The example file `image00427` is in the world coordinate system (this description may not be rigorous), while `test1_0` are transformed to image space to overlap with face in the original image.

**Comment by SunnyDp** [comment]
Thanks for your reply. But I can not figure out the world coordinate system and the image space. How can I get the same results as you showed？Please give me some specific tips. Thanks a lot.

**Comment by cleardusk** [comment]
Y-axis of the image space is toward below direction; while it is toward up in default. Be careful about it will be ok.

**Comment by FunkyKoki** [comment]
> Y-axis of the image space is toward below direction; while it is toward up in default. Be careful about it will be ok.

About this, I have a question. In https://github.com/cleardusk/3DDFA/blob/e44cd27fbef0feb71cc770bf05a1961bca13c423/utils/ddfa.py#L54 ,
you use `vertex[1, :] = std_size + 1 - vertex[1, :]` to do the transform, while I think it should be `vertex[1, :] = std_size - 1 - vertex[1, :]`.
Take a simple image with 4 pixels with both width and height equals to 2. It seems the new Y-axis coordinate should be `1 - original_y_axis_coord`.
Am I make a mistake here?
