### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'res/params_aflw2000.npy'

### ISSUE THREAD

**Issue by KhanhDinhDuy** [cleardusk/3DDFA#3]
Hello cleardusk,
Could you please help me with this error?
I can not find this file any where: "params_aflw2000.npy"
Thank you,
Khanh

**Comment by cleardusk** [comment]
You can check [this function](https://github.com/cleardusk/3DDFA/blob/master/visualize.py#L16). The `params_aflw2000.npy` is generated by it.

**Comment by KhanhDinhDuy** [comment]
Hello cleardusk,
Thank you so much,
Khanh
