### ISSUE TITLE
isRotationMatrix returns False!

### ISSUE THREAD

**Issue by cnaaq** [cleardusk/3DDFA#30]
Hi,

I tried the following code to get the rotation matrix and check if it is a rotation matrix or not, and if so, I get the three rotation angles from it. Suprisingly, `isRotationMatrix` that you introduced in one of the issues returns False. Here's my code:

`annotation = np.load('path/to/param_all_norm.pkl')`
`pose_params = annotations[0][-12:]`
`pose_params = pose_params.reshape((3, 4))`
`print(isRotationsMatrix(pose_params[:, 0:3]))`

do you have any idea?

Thanks!

**Comment by developer-mayuan** [comment]
I think the scale factor is embedded in the rotation matrix, so the determinant of the rotation matrix is not 1.

**Comment by cleardusk** [comment]
Right, the scale factor is embedded in the rotation matrix. For pose estimation, see [here](https://github.com/cleardusk/3DDFA/blob/master/utils/estimate_pose.py).
