### ISSUE TITLE
 caffe model

### ISSUE THREAD

**Issue by sunjunlishi** [cleardusk/3DDFA#33]

**Comment by cleardusk** [comment]
No

**Comment by sunjunlishi** [comment]
i want to change to caffe model,need i write the pytorch params by my self?

**Comment by sunjunlishi** [comment]
你的模型是 rar格式，为啥解压不了啊

**Comment by sunjunlishi** [comment]
https://github.com/anhttran/3dmm_cnn 你的文章和这篇非常相似，你使用了mobilenet.
但是他的输出参数，要乘以一个 100多M的模型。
你的要乘以那个精简的bfm模型3M多？

**Comment by cleardusk** [comment]
1. 模型是 pickle 二进制格式，不是 rar;
2. 关于移植到手机端，有不少人问过；该项目的初衷是作为一个学术研究内容发布，工程性的东西暂不考虑。

**Comment by sunjunlishi** [comment]
对了，请教个问题。我现在获得你的形状变化参数，要3d重构。要乘以的模型大小是多少 ？是哪个 100多M的3d标准模型吗？
