### ISSUE TITLE
Complete head reconstruction from a given 2D image.

### ISSUE THREAD

**Issue by naren142** [cleardusk/3DDFA#36]
Hi, is it possible to get the complete head of the human from a given 2D image which includes hair and neck with this code?
Thanks.

**Comment by cleardusk** [comment]
The code is updated. As for complete head, no.

**Comment by kekedan** [comment]
> Hi, is it possible to get the complete head of the human from a given 2D image which includes hair and neck with this code?
> Thanks.
dou you have any idea? we c can communicate about this, I also want to konw how to get the complete head of the human from a given 2D image.

**Comment by zhuchuanwu** [comment]
我们也在找类似的解决方案
