### ISSUE TITLE
can't import mesh_core_cython

### ISSUE THREAD

**Issue by tomy-k** [cleardusk/3DDFA#37]
After building cython module, the error message "ImportError: cannot import name 'mesh_core_cython" was showed.
What can I do??

**Comment by cleardusk** [comment]
Could you provide more information like the Python version, import error?

**Comment by tomy-k** [comment]
python ver3.6.2
macOS10.14

the errot message
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    from utils.render import get_depths_image, cget_depths_image, cpncc
  File "/Users/(my account)/Desktop/3DDFA/utils/render.py", line 17, in <module>
    from .cython import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython'

**Comment by cleardusk** [comment]
Is the binary file like`mesh_core_cython.cpython-37m-darwin.so` generated successfully?

**Comment by tomy-k** [comment]
I have done grep, but the file doesn't exit.

**Comment by cleardusk** [comment]
You may install Cython first,
```
sudo pip3 install cython
```
Then cd into `utils/cython`, build it
```
python3 setup.py build_ext -i
```
If the *.so is generated on current directory, everything will be ok.

**Comment by tomy-k** [comment]
already installed Cython
After building it,  ↓error messages was showed.

the error message
""""""""""""""""""""""""
   running build_ext
   skipping 'mesh_core_cython.cpp' Cython extension (up-to-date)
   building 'mesh_core_cython' extension
   gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwra
    pv -O3 -Wall -Wstrict-prototypes -I/Users/(myaccount)/anaconda3/include -a
    rch x86_64 -I/Users/(myaccount)/anaconda3/include -arch x86_64 -I/Users/(m
    yaccount)/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/User
    s/(myaccount)/anaconda3/include/python3.6m -c mesh_core_cython.cpp -o buil
    d/temp.macosx-10.7-x86_64-3.6/mesh_core_cython.o
   warning: include path for stdlibc++ headers not found; pass '-std=libc++'
    on
         the command line to use the libc++ standard library instead
         [-Wstdlibcxx-not-found]
   In file included from mesh_core_cython.cpp:624:
   In file included from /Users/(myaccount)/anaconda3/lib/python3.6/site-pack
    ages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/(myaccount)/anaconda3/lib/python3.6/site-pack
    ages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /Users/(myaccount)/anaconda3/lib/python3.6/site-pack
    ages/numpy/core/include/numpy/ndarraytypes.h:1823:
  /Users/(myaccount)/anaconda3/lib/python3.6/site-packages/numpy/core/includ
    e/numpy/npy_1_7_deprecated_api.h:15:2: warning:
        "Using deprecated NumPy API, disable it by "          "#defining
        NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  mesh_core_cython.cpp:626:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  2 warnings and 1 error generated.
  error: command 'gcc' failed with exit status 1

"""""""""""""""""""""""""""""""""""""""""""

**Comment by cleardusk** [comment]
You may update your Command Line Tools on macOS. But I am not sure for it.

**Comment by tomy-k** [comment]
I used "iTerm2"
but it is up to date...
so, I can't found the source of the error.

**Comment by cleardusk** [comment]
No feedback.

**Comment by zhangdm** [comment]
hi，this is my issue with mac ,

(3Dven) zhangxMacBook-Air:3DDFA zhangxiang$ python3 ./main.py -f samples/emma_input.jpg --bbox_init=two --dlib_bbox=false
Traceback (most recent call last):
  File "./main.py", line 25, in <module>
    from utils.render import get_depths_image, cget_depths_image, cpncc
  File "/Users/zhangx/tf/3DDFA/utils/render.py", line 17, in <module>
    from .cython import mesh_core_cython
  File "__init__.pxd", line 918, in init mesh_core_cython

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject


the directory trees :
(3Dven) zhangxdeMacBook-Air:cython zhangxiang$ tree
.
├── __init__.py
├── __pycache__
│   └── __init__.cpython-36.pyc
├── build
│   └── temp.macosx-10.7-x86_64-3.6
│       ├── mesh_core.o
│       └── mesh_core_cython.o
├── mesh_core.cpp
├── mesh_core.h
├── mesh_core_cython.cpp
├── mesh_core_cython.cpython-36m-darwin.so
├── mesh_core_cython.pyx
├── readme.md
└── setup.py

thanks.

**Comment by yuemengyuan** [comment]
Hello, I have encountered the same problem as you. Can you solve it? @

**Comment by yuemengyuan** [comment]
> 
> 
> hi，this is my issue with mac ,
> 
> (3Dven) zhangxMacBook-Air:3DDFA zhangxiang$ python3 ./main.py -f samples/emma_input.jpg --bbox_init=two --dlib_bbox=false
> Traceback (most recent call last):
> File "./main.py", line 25, in
> from utils.render import get_depths_image, cget_depths_image, cpncc
> File "/Users/zhangx/tf/3DDFA/utils/render.py", line 17, in
> from .cython import mesh_core_cython
> File "**init**.pxd", line 918, in init mesh_core_cython
> 
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
> 
> the directory trees :
> (3Dven) zhangxdeMacBook-Air:cython zhangxiang$ tree
> .
> ├── **init**.py
> ├── **pycache**
> │   └── **init**.cpython-36.pyc
> ├── build
> │   └── temp.macosx-10.7-x86_64-3.6
> │   ├── mesh_core.o
> │   └── mesh_core_cython.o
> ├── mesh_core.cpp
> ├── mesh_core.h
> ├── mesh_core_cython.cpp
> ├── mesh_core_cython.cpython-36m-darwin.so
> ├── mesh_core_cython.pyx
> ├── readme.md
> └── setup.py
> 
> thanks.

Hello, I have encountered the same problem as you. Can you solve it?

**Comment by yuemengyuan** [comment]
Hello, I have encountered the same problem as you. Can you solve it? @zhangdm

**Comment by azhaoaigaga** [comment]
Hello, I have encountered the same problem as you. Can you solve it? @yuemengyuan

**Comment by jordanfranklin1** [comment]
Sorry if this is a stupid question, but I am having trouble with installing this module and received this error message:

ModuleNotFoundError: No module named 'mesh_core_cython'

How to install it on Ubuntu command line? I also have pip installed.
