### ISSUE TITLE
Question of ZBuffer.m of your paper code Face Alignment Across Large Poses: A 3D Solution

### ISSUE THREAD

**Issue by Wangshuiquan** [cleardusk/3DDFA#38]
Hello,could you tell me what's the meaning of the parameter 's2d' in the code of your paper Face Alignment Across Large Poses: A 3D Solution. What does it stand for?
Thank you!

**Comment by cleardusk** [comment]
Sorry for that I do not maintain the matlab code in paper "Face Alignment Across Large Poses: A 3D Solution". You should ask [XiangyuZhu](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/).
