### ISSUE TITLE
Some detail question

### ISSUE THREAD

**Issue by hanxiaoyaoer** [cleardusk/3DDFA#40]
Dear author, when refer to 3D face reconstuction, i see in your main.py which could only generate vertex list, could it generate texture list?

**Comment by cleardusk** [comment]
You can refer to `Getting started` part. After running`python3 main.py -f samples/test1.jpg`, the output `samples/test1_0.obj` contains the sampled texture list.

**Comment by cleardusk** [comment]
The `.obj` file is visualized by `meshlab`, NOT matlab. If you want to visualize 3D data using python, you may refer to opengl or light-weight (may limited) lib [face3d](https://github.com/YadiraF/face3d).
