### ISSUE TITLE
comparison with FAN method

### ISSUE THREAD

**Issue by cristinasegalin** [cleardusk/3DDFA#41]
Hi, 
thank you for your contribution on this topic.
I am curious to understand how this improved implementation performs w.r.t FAN approach from "How far are we from solving the 2D \& 3D Face Alignment problem? (and a dataset of 230,000 3D facial landmarks"  work.

thank you.

**Comment by cleardusk** [comment]
It depends. FAN methods are not dense face alignment while 3DDFA can regress dense face vertices. You have proposed the same issue in [here](https://github.com/1adrianb/face-alignment/issues/122), the author of FAN has a good response. In all, these two methods have their own advantages.
