### ISSUE TITLE
how to generate two styles in obama_three_styles.gif

### ISSUE THREAD

**Issue by gara-MI** [cleardusk/3DDFA#43]
Hey @cleardusk 
I have a question regarding the Gif image `obama_three_styles.gif`, 
Can you please explain how you generated two stlyes  overlays in this GIF, I understood about the  dlib facial points. I am kind of new to this topic. But I couldn't grasp how you are generating the fist two styles. Are they depth map and PNCC represented in different color ?

Thanks in advance

**Comment by cleardusk** [comment]
Just use the surface and point cloud drawing functions in Matlab. They are 3D mesh and 3D point clouds.

**Comment by bleakie** [comment]
Hey：
How can I get such a 2D face mask？

**Comment by cleardusk** [comment]
The main.py provides the 3D face mesh reconstruction function. Is the rendered 3D face mesh the face mask you mean?

**Comment by bleakie** [comment]
I mean how to get 2D face mesh reconstruction function or 2D face mesh the face mask？

**Comment by cleardusk** [comment]
Just ignore the z-axis value, the 3D mesh becomes 2D mesh.

**Comment by bleakie** [comment]
Why STD_SIZE=120？

**Comment by bleakie** [comment]
Thank you for your reply：
When the mouth opens, it will pick out the pixels on the mouth. What can we do without manipulating the pixels?

**Comment by cleardusk** [comment]
1. The input image size is 120x120.
2. I do not understand your question. Could you give a more clear description?

**Comment by XgTu** [comment]
I also have this question, how to get the mask of the two styles for obama ?
![image](https://user-images.githubusercontent.com/8948023/53696045-049e9500-3dfe-11e9-882d-b71a5a0bcc11.png)
![image](https://user-images.githubusercontent.com/8948023/53696046-08cab280-3dfe-11e9-9f9f-bef3b44dffe5.png)
I know I should use the surface and point cloud drawing functions in Matlab, could you paste the relevant code ?
Thanks very much in advance!

**Comment by cleardusk** [comment]
Mesh rendering: refer to the `patch` function in Matlab.
Point cloud visualization: refer to the `pcshow` function in Matlab.
The complete code maybe added in the future.

**Comment by thimabru1010** [comment]
> Mesh rendering: refer to the `patch` function in Matlab.
> Point cloud visualization: refer to the `pcshow` function in Matlab.
> The complete code maybe added in the future.

How can I actually visualize the 3d Point Cloud mask generated in dump_vertex argument on main.py ? there isn't any function in python that provides this?
