### ISSUE TITLE
run main.py error

### ISSUE THREAD

**Issue by jackweiwang** [cleardusk/3DDFA#44]
python main.py  -f samples/test1.jpg

Traceback (most recent call last):
  File "/home/ww/3DDFA/main.py", line 205, in <module>
    main(args)
  File "/home/ww/3DDFA/main.py", line 45, in main
    model.load_state_dict(model_dict)
  File "/home/ww/anaconda3/envs/Stacked_Hourglass_Network_Keras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MobileNet:
	Unexpected key(s) in state_dict: "bn1.num_batches_tracked", "dw2_1.bn_dw.num_batches_tracked", "dw2_1.bn_sep.num_batches_tracked", "dw2_2.bn_dw.num_batches_tracked", "dw2_2.bn_sep.num_batches_tracked", "dw3_1.bn_dw.num_batches_tracked", "dw3_1.bn_sep.num_batches_tracked", "dw3_2.bn_dw.num_batches_tracked", "dw3_2.bn_sep.num_batches_tracked", "dw4_1.bn_dw.num_batches_tracked", "dw4_1.bn_sep.num_batches_tracked", "dw4_2.bn_dw.num_batches_tracked", "dw4_2.bn_sep.num_batches_tracked", "dw5_1.bn_dw.num_batches_tracked", "dw5_1.bn_sep.num_batches_tracked", "dw5_2.bn_dw.num_batches_tracked", "dw5_2.bn_sep.num_batches_tracked", "dw5_3.bn_dw.num_batches_tracked", "dw5_3.bn_sep.num_batches_tracked", "dw5_4.bn_dw.num_batches_tracked", "dw5_4.bn_sep.num_batches_tracked", "dw5_5.bn_dw.num_batches_tracked", "dw5_5.bn_sep.num_batches_tracked", "dw5_6.bn_dw.num_batches_tracked", "dw5_6.bn_sep.num_batches_tracked", "dw6.bn_dw.num_batches_tracked", "dw6.bn_sep.num_batches_tracked". 

can you give me some advice maybe the 'phase1_wpdc_vdc_v2.pth.tar' missing parameters?

**Comment by cleardusk** [comment]
With PyTorch 0.4.1, everything is OK. I can not reproduce your situation. You can provide more information or go through requirements.txt first?

**Comment by jackweiwang** [comment]
Thanks， i solved it, used Pytorch 0.4.1
