### ISSUE TITLE
Have you realsed the data pre-processing code?

### ISSUE THREAD

**Issue by mehameha998** [cleardusk/3DDFA#45]
Hello @cleardusk , Thanks for your fantistic reproducttion. 
I am going to compare my own method with 3DDFA in another dataset. However, I'm not sure the data pre-processing method, espacially about pose and shape parameters. For example, the official data of ALFW is unormalized, and the vector length is longer than yours. So could you briefly introduce the normalize method and the way the choose the dimension of parameters? 
THANKS!

**Comment by mehameha998** [comment]
My Guess: the standard mean value and variance are computed using the whole training set. Am I right?

**Comment by cleardusk** [comment]
Right.

**Comment by ZHJNCUT** [comment]
Are you aware of this? The pose parameter of the 300W-LP dataset is 7 dimensional
However, in the implementation code of the 3DDFA paper, the 12 dimensions of regression are used directly
I don't know the connection, do you know this? There are many people asking this question on github, but I can't find the answer, can you help me

**Comment by Hamidoullah** [comment]
It's been a while since I last worked on ClearDusk/3DDFA.
