### ISSUE TITLE
about WPDC,why do you set weight[0:12] to zeor? and 3dmm parameters should be 235 dims but 62 dims in your project?

### ISSUE THREAD

**Issue by shoutOutYangJie** [cleardusk/3DDFA#47]
about WPDC,why do you set weight[0:12] to zeor? 
and 3dmm parameters should be 235 dims but 62 dims in your project?
and wpdc loss uses many '.npy' files .What are these files?

**Comment by cleardusk** [comment]
Sorry for that, the training details will be updated in the next two months.
