### ISSUE TITLE
How to generate the 3D reconstruction results

### ISSUE THREAD

**Issue by XgTu** [cleardusk/3DDFA#49]
Hi, 
I wonder how to generate the 3D reconstruction results shown below:
![image](https://user-images.githubusercontent.com/8948023/53695989-54309100-3dfd-11e9-99d5-147ebad7616f.png)
![image](https://user-images.githubusercontent.com/8948023/53695991-5bf03580-3dfd-11e9-9adb-32915be05082.png)
Should I use matlab or other tools?

**Comment by cleardusk** [comment]
#43
