### ISSUE TITLE
generate 3D mesh pics

### ISSUE THREAD

**Issue by lvvvmd** [cleardusk/3DDFA#5]
Hi jianzhu,
    I am a student from Zhejiang University and I have successfully run your code but I can't generate the pics with 3D mesh like imgs/vertex_3d.jpg by running visualize.py.
    It would be greatly appreciated if you can tell me where is the code for offscreen 3D rendering to generate imgs/vertex_3d.jpg!
    Thank you very much!
 
Besh wishes,
Minda.

**Comment by cleardusk** [comment]
I use Matlab for the offscreen 3D rendering. Specifically, `trisurf` function is for 3D mesh rendering.

**Comment by lvvvmd** [comment]
OK! Thank you very much!
