### ISSUE TITLE
question about reproduce

### ISSUE THREAD

**Issue by zhiji666** [cleardusk/3DDFA#50]
Thanks for your wonderful job! Does it work for animal (like dog or cat) face alignment? I mean, change the training data and training by the same method. What's your advice?

**Comment by cleardusk** [comment]
Sorry for that this issue may be beyond the scope of this repo.
Essentially, this method is data-driven, so that if you have data, you can use it. But I think this method may not work because no face model like BFM is built for dog or cat.

**Comment by tiancaipipi110** [comment]
@cleardusk 

> no face model like BFM is built for dog or cat

Do you might know a demo/article showing how to build one?

**Comment by tiancaipipi110** [comment]
Specifically how to register and parameterize a model. <a href ='https://gravis.dmi.unibas.ch/publications/2009/BFModel09.pdf'>BFModel09</a> suggested Optimal Step Nonrigid ICP Algorithm, but no details.
