### ISSUE TITLE
Which is more accurate? 3DDFA or PRNet?

### ISSUE THREAD

**Issue by yxchng** [cleardusk/3DDFA#51]
I saw that you credited PRNet in this repo. Can I know if you have any idea which is more accurate? Thanks.

**Comment by cleardusk** [comment]
As for **this repo** and officail PRNet, the performance of the latter one is better, but the former maybe 20x faster than the latter one.

**Comment by lbc402** [comment]
@cleardusk Is the reason why this repo is faster than prnet is because it uses a smaller input image size and a smaller model（mobilenet）？

**Comment by cleardusk** [comment]
You can see the updated readme. This improved version can run at a very fast speed with even better performance than PRNet. Relevant work is under review.

**Comment by tetterl** [comment]
@cleardusk Any estimate when the relevant work will be published and be uploaded to GitHub? Is it correct that it will provide better 3D reconstruction than PRNet?
