### ISSUE TITLE
what is your trainingset?

### ISSUE THREAD

**Issue by wqz960** [cleardusk/3DDFA#52]

**Comment by cleardusk** [comment]
The training set is 300W-LP and you can read readme.md or the original paper for more details

**Comment by wqz960** [comment]
你好作者！我看了你的训练集，你能提供你的preprocess脚本吗，还有一个问题，我看了300W_Lp的mat，这输出对应的是那些值啊，感觉没有62（12,40,10)的参数，不知道target是什么。刚刚学，对输入输出都不太了解，初始输入的pncc是同一个吗，然后通过network得到的param重建新的吗？@cleardusk 非常感谢！
