### ISSUE TITLE
Possible error in "matrix2angle" function?

### ISSUE THREAD

**Issue by yxchng** [cleardusk/3DDFA#53]
Your code:

> def matrix2angle(R):
>     ''' compute three Euler angles from a Rotation Matrix. Ref: http://www.gregslabaugh.net/publications/euler.pdf
>     Args:
>         R: (3,3). rotation matrix
>     Returns:
>         x: yaw
>         y: pitch
>         z: roll
>     '''
>     # assert(isRotationMatrix(R))
> 
>     if R[2, 0] != 1 or R[2, 0] != -1:
>         x = asin(R[2, 0])
>         y = atan2(R[2, 1] / cos(x), R[2, 2] / cos(x))
>         z = atan2(R[1, 0] / cos(x), R[0, 0] / cos(x))
> 
>     else:  # Gimbal lock
>         z = 0  # can be anything
>         if R[2, 0] == -1:
>             x = np.pi / 2
>             y = z + atan2(R[0, 1], R[0, 2])
>         else:
>             x = -np.pi / 2
>             y = -z + atan2(-R[0, 1], -R[0, 2])
> 
>     return x, y, z
> 

Reference:

![Screenshot from 2019-03-25 09-14-24](https://user-images.githubusercontent.com/10518587/54889237-9457d080-4ede-11e9-816a-4a09dc76818a.png)

Hi I checked your estimate_pose.py code with the reference `http://www.gregslabaugh.net/publications/euler.pdf` and it seems that x is supposed to be `x = -asin(R[2,0])`? Is this a bug? Or is there any special reason to remove the negative sign? If so, can you explain why the sign is removed? Thanks!

**Comment by cleardusk** [comment]
It seems that the estimated pose is just OK. Maybe it is for consistency. I did not check it detailly and if you find the estimated result is wrong, you can report it as a bug.

**Comment by FunkyKoki** [comment]
> Your code:
> 
> > def matrix2angle(R):
> > ''' compute three Euler angles from a Rotation Matrix. Ref: http://www.gregslabaugh.net/publications/euler.pdf
> > Args:
> > R: (3,3). rotation matrix
> > Returns:
> > x: yaw
> > y: pitch
> > z: roll
> > '''
> > # assert(isRotationMatrix(R))
> > ```
> > if R[2, 0] != 1 or R[2, 0] != -1:
> >     x = asin(R[2, 0])
> >     y = atan2(R[2, 1] / cos(x), R[2, 2] / cos(x))
> >     z = atan2(R[1, 0] / cos(x), R[0, 0] / cos(x))
> > 
> > else:  # Gimbal lock
> >     z = 0  # can be anything
> >     if R[2, 0] == -1:
> >         x = np.pi / 2
> >         y = z + atan2(R[0, 1], R[0, 2])
> >     else:
> >         x = -np.pi / 2
> >         y = -z + atan2(-R[0, 1], -R[0, 2])
> > 
> > return x, y, z
> > ```
> 
> Reference:
> 
> ![Screenshot from 2019-03-25 09-14-24](https://user-images.githubusercontent.com/10518587/54889237-9457d080-4ede-11e9-816a-4a09dc76818a.png)
> 
> Hi I checked your estimate_pose.py code with the reference `http://www.gregslabaugh.net/publications/euler.pdf` and it seems that x is supposed to be `x = -asin(R[2,0])`? Is this a bug? Or is there any special reason to remove the negative sign? If so, can you explain why the sign is removed? Thanks!

As I can see from the code, the pose is not used at anywhere. So the bug has no influence.
