### ISSUE TITLE
your implementation has big difference from the 3DDFA paper

### ISSUE THREAD

**Issue by maliho0803** [cleardusk/3DDFA#54]
the implementation is very different from the origin paper?
the input of your training is just the 2d images, but the input is more complicated described in origin paper(Image + PNCC, image + anchors), why not using PNCC and anchors in your implementation?

**Comment by maliho0803** [comment]
the input of your training is just the 2d images, but the input is more complicated described in origin paper, as below graph.

**Comment by cleardusk** [comment]
So it is called the improved version. Because only single inputs can get promising results.

**Comment by maliho0803** [comment]
Hi, one more questions, when I use your official face profiling code, the teeth of the generated face image is very weird， could you tell me why?

**Comment by cleardusk** [comment]
Face profiling code is wroten by [Xiangyu Zhu](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/). You can contact him for the details.
