### ISSUE TITLE
请问能解释下下面的这些文件的作用和怎么制作的吗？

### ISSUE THREAD

**Issue by yangdashi88** [cleardusk/3DDFA#58]
![360截图20190422164747787](https://user-images.githubusercontent.com/20290902/56492443-6934c100-651e-11e9-8f09-05a13d132f74.jpg)
请问能解释下上面图片里的这些文件的作用和怎么制作的吗？谢谢。

**Comment by cleardusk** [comment]
您好，作用可以根据文件名来解析；关于生成部分的代码由于还在维护中暂时无法开源。
