### ISSUE TITLE
offset_norm and  magic_number in wpdc_loss.py

### ISSUE THREAD

**Issue by ChunyanZhao** [cleardusk/3DDFA#6]
Hi, @cleardusk 
Thank you for your code.
I am confused about the value of these two variables, offset_norm and  magic_number. Would you please tell me how do you select them?

**Comment by cleardusk** [comment]
The original implementation is rather slow, therefore I optimized it for real-time training. `offset_norm` and `magic_number` are two intermediate variables.  You can regard WPDC loss as three parts: pose, shape, and expression. The offset_norm and magic_number are intermediate variables to calculate their weights. You don't need to select them. I will write a blog if more people are interested in it.

**Comment by zhww** [comment]
> The original implementation is rather slow, therefore I optimized it for real-time training. `offset_norm` and `magic_number` are two intermediate variables. You can regard WPDC loss as three parts: pose, shape, and expression. The offset_norm and magic_number are intermediate variables to calculate their weights. You don't need to select them. I will write a blog if more people are interested in it.

Thank you for your code.
The implementation of wpdc_loss seems different from the paper, will you give more detailed interpretation about it, especially:
1.  the **for ind in range(11)** block,
     why pose params are split into three parts: [0, 4, 8], [1, 5, 9], [2, 6, 10], and w of the param in a part multiply the same tmpv_norm's idx.
2.  magic_number
3.  **weights[:, 11] = 0**
