### ISSUE TITLE
Uncontrolled motion of the head

### ISSUE THREAD

**Issue by ABHIARIGE** [cleardusk/3DDFA#60]
Hello,
I tried to run the depth estimation for a video for a person who is talking but I have continuous motion of the head(like the shake of the head even though the person is not moving his head that much). May I know what could be the possible reasons.please find the attached gif
![test](https://user-images.githubusercontent.com/49910675/56589722-18889b00-65e6-11e9-8ed5-fac5413ca743.gif)

**Comment by cleardusk** [comment]
It maybe caused by the unstable detecting box. Could you please provide the original video?

**Comment by cleardusk** [comment]
Any feedback?
