### ISSUE TITLE
贴图问题

### ISSUE THREAD

**Issue by zhuchuanwu** [cleardusk/3DDFA#61]
您好 您的项目我今下午跑起来了 用我自己的照片生成模型也没问题 1 看历史问题 很多人也在提贴图问题 现在代码是否有这部分功能？ 2 如果想生成整个头部模型 是否有方案？我见过一个可以生成整个头部的模型的方案 他是脸部模型是单独的 头发是拼接起来的

**Comment by cleardusk** [comment]
You can refer to `Flame` model.
