### ISSUE TITLE
Some bugs in pytroch1.0.1

### ISSUE THREAD

**Issue by LucienXian** [cleardusk/3DDFA#63]
In this [line](https://github.com/cleardusk/3DDFA/blob/dea30ce24b53904b3044af591033e859c5d82bbf/train.py#L174) , we should remove it, and add code below:
`loss = torch.mean(torch.stack(losses))`
Otherwise, we will get an error: 
`in _mean ret = ret.dtype.type(ret / rcount), 
AttributeError: 'torch.dtype' object has no attribute 'type'`
Refer to: https://discuss.pytorch.org/t/get-the-mean-from-a-list-of-tensors/31989

**Comment by cleardusk** [comment]
Using `item()` [here](https://github.com/cleardusk/3DDFA/blob/master/train.py#L171) is OK. Tks for your feedback.
