### ISSUE TITLE
could you give me some clues about how to understand P2sRt?

### ISSUE THREAD

**Issue by KangolHsu** [cleardusk/3DDFA#64]
could you give me some clues about how to understand P2sRt  in the line below?
https://github.com/cleardusk/3DDFA/blob/5e2d051446302a0f885d32ad20e328118881f3be/utils/estimate_pose.py#L53

thanks

**Comment by cleardusk** [comment]
It is a function to decompose the camera matrix P to scale, rotation and offset.
