### ISSUE TITLE
mesh disorder

### ISSUE THREAD

**Issue by snowzhangy** [cleardusk/3DDFA#66]
hi.
   I met a problem when testing your program, when i render the mat it looks like this.
![QQ图片20190506155235](https://user-images.githubusercontent.com/9041987/57260201-74581880-7017-11e9-8123-e1f216a09c30.png)
  but if render the mat you provided , they works fine. 
  Hope you could help me.
thanks

**Comment by LucienXian** [comment]
@snowzhangy Hi, How to cover the input image with the obj model?

**Comment by snowzhangy** [comment]
> @snowzhangy Hi, How to cover the input image with the obj model?

the author has released a demo code (demo@obama) recently. just follow the instruction.

**Comment by cleardusk** [comment]
Is the problem solved? @snowzhangy

**Comment by LucienXian** [comment]
@cleardusk I got the same problem as @snowzhangy . I use the main.py to generate the .mat file. But the result does not work well as yours.

**Comment by cleardusk** [comment]
You can check the shape of the generated matrix first. This may be caused by shape dismatch.

**Comment by LucienXian** [comment]
@cleardusk  Are you referring to the size of the vertices? Yes, inconsistent sizes. So how do you process the  .mat files?

**Comment by cleardusk** [comment]
Try to transpose it?

**Comment by LucienXian** [comment]
@cleardusk Not for this reason. When I read the video file, the output vertices size of the frame is (53215, 3), but the .mat file you provided is (46859, 3). So how can we preprocess it?

**Comment by cleardusk** [comment]
Use the 53215x3 vertices matrix and `visualize/tri.mat` as triangle indices.

**Comment by LucienXian** [comment]
@cleardusk But in this [line](https://github.com/cleardusk/3DDFA/blob/e1b34959d41d9dbcdbf175eb5d1d09c37fed4794/demo%40obama/rendering.py#L45), the '.mat' file  is (46859, 3).  
But when we read the frame from the video, and do the inference, then get the output vertices is (53215, 3).
So before we use the indices, the vertices may be different?

**Comment by cleardusk** [comment]
53215x3 -> `visualize/tri.mat`;
46859x3 -> `demo@obama/tri_refine.mat`.

**Comment by LucienXian** [comment]
Ok, I will try it!! 
Another question, could the file demo@obama/tri_refine.mat  be applied into  any video? And what does it mean?

**Comment by cleardusk** [comment]
Use `tri.mat`, not `tri_refine.mat`. The previous can be applied to any image or video.

**Comment by LucienXian** [comment]
When I use the `tri.mat`, the img_render is an original image.
This is my script, any problem?
```python
    app = RenderPipeline(**cfg)
    init()
    # tri = sio.loadmat('tri_refine.mat')['tri']  # mx3
    tri = sio.loadmat('../visualize/tri.mat')['tri']
    triangles = _to_ctype(tri).astype(np.int32)  # for type compatible

    i = 0
    frame_rate = 6
    prev = 0
    while True:
        time_elapsed = time.time() - prev
        ret, frame = video_capture.read()
        if time_elapsed > 1. / frame_rate:
            prev = time.time()
            i += 1
            # img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img = frame
            vertices = get_vertices(wd, img)
            if vertices is None:
                continue
            vertices = vertices.T.copy(order='C')
            img = img.astype(np.float32) / 255.
            img_render = app(vertices, triangles, img)
            print(i)

            # if i % 10 == 0:
                # cv2.imwrite('test'+str(i)+'.jpg', img_render)

            cv2.imshow('Video', img_render)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

    video_capture.release()
    cv2.destroyAllWindows()
```

**Comment by LucienXian** [comment]
@cleardusk Hi, thx for your help. But I got soma extra problem. Maybe the visualize/tri.mat dismatch with the vertices? Like this, the eyes and the extra long long triangle:
![WechatIMG22](https://user-images.githubusercontent.com/22817327/58159594-6ceb6d00-7caf-11e9-8f4e-2248f45251b1.jpeg)

**Comment by cleardusk** [comment]
Sorry for that I had no time to tackle this issue these days.

**Comment by cleardusk** [comment]
Close as no feedback is provided.
