### ISSUE TITLE
How to get the ground truth p?

### ISSUE THREAD

**Issue by tjusxh** [cleardusk/3DDFA#68]
Thanks for your big contribution. I have a question, when you training the network, how to get the ground truth p corresponding for the image? My guess: you got them by fitting 3dmm. is it right?

**Comment by cleardusk** [comment]
The ground-truth is from [300W-LP](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/Database/300W-LP/main.htm) dataset. You can also generate them by 3DMM fitting as you said.
