### ISSUE TITLE
error happens when I run benchmark.py

### ISSUE THREAD

**Issue by yyssmm** [cleardusk/3DDFA#7]
Thank you for sharing your code. But I meet an error like this : 
map_location = {f'cuda:{i}': 'cuda:0' for i in range(8)}   me 
                             ^
SyntaxError: invalid syntax 
Would you please tell me what I should do. Thank you

**Comment by cleardusk** [comment]
Are your Python version 3.6.x？This syntax error maybe the string format of `f''`
