### ISSUE TITLE
vertex number of face model?

### ISSUE THREAD

**Issue by MrBurnst** [cleardusk/3DDFA#71]
I'm having trouble with the number of vertices in the face model. Basically, I would like a uv-mapping of the model, and there is one for the BFM available online, but the vertex numbers do not match with your model. yours has 53215 vertices, and the BFM has 53490 - where did the 275 vertices go? what model did you use?

**Comment by cleardusk** [comment]
Forspecific pre-processing details, you can refer to [here](https://github.com/YadiraF/face3d/tree/master/examples/Data/BFM).
