### ISSUE TITLE
Evaluated with 3d coordinate result

### ISSUE THREAD

**Issue by Kiris-Wu** [cleardusk/3DDFA#75]
Hi, I'm new in face alignment. I found that in the benchmark testing code, when calculating NME we are using [:2,:] to project the 3d result into 2d. Since in the paper people are using to present both 2d and 3d 68-point NME results, I wonder if we want to test with 3d coordinate directly, should we just remove the :2 and use the whole coordinate?

**Comment by cleardusk** [comment]
If you want to test 3d coordinates, you may first translate the z-axis to make sure the lowest z-value is zero.

**Comment by Kiris-Wu** [comment]
@cleardusk  Hi, I'm sorry to reopen the issue again! When testing the network I found the prediction of z-axis has big difference between using cropped images and whole images. E.g. [124,170,81] for whole images test and [15,20,32] for cropped test. We have coordinate transformation for x and y axis. Do we need to do such transformation for z?
