### ISSUE TITLE
About expression

### ISSUE THREAD

**Issue by 1icas** [cleardusk/3DDFA#77]
Jianzhu:
你好，我想了解一下关于每张图片的形状参数和表情参数是如何生成的哈。 我没有找到这部分源码。 如果目前未开源的话，请问一下，是借鉴了哪篇文献中的思路对图片进行处理的呢？ 谢谢

**Comment by cleardusk** [comment]
通过传统拟合生成的；具体文献参考 3dmm fitting 关键字的文章。
