### ISSUE TITLE
Some questions about the sample method in your loss file

### ISSUE THREAD

**Issue by xjcvip007** [cleardusk/3DDFA#81]
Hi, cleardusk, thanks for your amazing job!
I have some questions for you, in your vdc_loss.py and wpdc_loss.py, you use forward_resample instead of forward_all method, and set resample_num with 132 default.
(1) why you use resample method instead of use keypoint sample method? Does it to better alignment error?
(2) if so, how to set resample_num in your experience? why not set 68*2=136 but 132?
Looking for your replying~

**Comment by cleardusk** [comment]
1. Resample is to accelerate the training.
2. 132 means 132 points, not 132/2 points. See [here](https://github.com/cleardusk/3DDFA/blob/master/training/train_vdc.sh#L18).
