### ISSUE TITLE
关于expMU的困惑！！

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [cleardusk/3DDFA#82]
大佬，我对expMU不是很明白

model['shapeMU'] = (model['shapeMU'] + model['expMU']).astype(np.float32)

其他的方法中并没有提及这个参数，并且我拟合系数的时候也米有发现使用expMU和不使用expMU的却别，视觉效果是差不多的。。求解答

![image](https://user-images.githubusercontent.com/30692249/63225317-f3f1a800-c200-11e9-8cf0-ab66f2d3acec.png)
![image](https://user-images.githubusercontent.com/30692249/63225337-492db980-c201-11e9-969a-48b8f1be73bc.png)

**Comment by cleardusk** [comment]
```model['shapeMU'] = (model['shapeMU'] + model['expMU']).astype(np.float32)```这行代码并不在本 repo 中；请提供一个清晰的issue描述

**Comment by ZHANG-SHI-CHANG** [comment]
> `model['shapeMU'] = (model['shapeMU'] + model['expMU']).astype(np.float32)`这行代码并不在本 repo 中；请提供一个清晰的issue描述

shapeMU对应这u_exp.npy这个文件，想请教下这个文件的作用和获得方法，因为我在用facewarehouse表情基拟合系数的时候没有发现大的区别。。。

**Comment by ZHANG-SHI-CHANG** [comment]
我知道原因了，建议去掉它，它会导致netural face也出现张嘴的现象

**Comment by jimmysue** [comment]
> 我知道原因了，建议去掉它，它会导致netural face也出现张嘴的现象

我同样对这个 [u_exp](https://github.com/cleardusk/3DDFA/blob/master/train.configs/u_exp.npy) 感到困惑。 我的猜测是，这个平均值来源于所有的表情mesh减去 u_shp 之后的均值。 如果不加这个均值，表情基就会缺少一个 bias。 不知道这样的理解对不对 @cleardusk
