### ISSUE TITLE
Could you provide an explanation of parameters in params.py ?

### ISSUE THREAD

**Issue by MoMe36** [cleardusk/3DDFA#83]
Hi ! Thanks for your amazing work. 
I'd like to use it as a base for further works. Could you please provide an explanation for the numpy matrices loaded in `params.py` ? In particular: 
* Keypoints
* w_shp
* w_exp
* u_shp
* u_exp

I could be wrong but I am under the impression that these are base mesh data that are then deformed by the network's prediction. 

Thanks a lot for your help !

**Comment by cleardusk** [comment]
U are right, w_shp and w_exp are the shape and expression basis; u_shp and u_exp are the mean.

**Comment by MoMe36** [comment]
Thanks ! 
But I don't understand the shapes. For instance, given that the `obj` mesh has 159645 vertices what does these represent ? 
```
kp - (204,)
w_shp - (159645, 40)
w_exp - (159645, 10)
param_mean - (62,)
u_shp - (159645, 1)
u_exp - (159645, 1)
```

**Comment by cleardusk** [comment]
159645 / 3 = 53215 vertices

**Comment by MoMe36** [comment]
This I understand. But what about the 40 columns in `w_shp, w_exp`?

**Comment by cleardusk** [comment]
It is the 3DMM basis constructed by PCA, the original shape is 159645x199 but I remove the last 159 dimensions to perform acceleration, which has little effect on the reconstructed face.

**Comment by jimmysue** [comment]
> U are right, w_shp and w_exp are the shape and expression basis; u_shp and u_exp are the mean.

Why there's u_shp and u_exp separately？ What 's the meaning of u_exp here ?
