### ISSUE TITLE
Process multiple pictures but keep going when finding errors

### ISSUE THREAD

**Issue by AndroXD** [cleardusk/3DDFA#84]
Hello,
I'm trying to process multiple pictures using main.py, some will work flawlessly, but others will throw this error and stop the entire process:

`Traceback (most recent call last):
  File "main.py", line 205, in <module>
    main(args)
  File "main.py", line 71, in main
    lines = open(rect_fp).read().strip().split('\n')[1:]
FileNotFoundError: [Errno 2] No such file or directory: 'img_dir\\00001.png.bbox'`

I need to process more than 20.000 pictures in a folder, I'm using this command "python main2.py -f img_dir\00001.png img_dir\00002.png img_dir\00003.png ..." in a batch process, but if picture "00002.png" were to throw an error, the entire process would stop and ignore the next pictures in the list, if I do them singularly in batch like this "python main2.py -f img_dir\00001.png ; python main2.py -f img_dir\00002.png ; python main2.py -f img_dir\00001.png" it would work but get a lot slower. Is there a way to ignore errors and keep going anyway?

**Comment by cleardusk** [comment]
I suggest you catch the exceptions in the loop. If an error occurs, print it and continue the loop.
