### ISSUE TITLE
No neck index

### ISSUE THREAD

**Issue by yfji** [cleardusk/3DDFA#86]
Hi! Where can I find the indices without the neck? The face area and ears needs to be included

**Comment by cleardusk** [comment]
Due to the limit of the license, I can not redistribute the modified BFM, therefore I can not release it now. I am sorry for that.

**Comment by yfji** [comment]
Thanks for your quick reply.  Can you teach me how to select arbitrary points I want from more than 50k points? Thanks!发自我的华为手机-------- 原始邮件 --------主题：Re: [cleardusk/3DDFA] No neck index (#86)发件人：Jianzhu Guo 收件人：cleardusk/3DDFA <3DDFA@noreply.github.com>抄送：yfji ,Author Due to the limit of the license, I can not redistribute the modified BFM, therefore I can not release it now. I am sorry for that.

**Comment by cleardusk** [comment]
You can use meshlab to filter out unneeded points.
