### ISSUE TITLE
请问如何利用 main.py --dump_vertex   = true 生产的 .mat文件来渲染脸部轮廓？

### ISSUE THREAD

**Issue by guiweit** [cleardusk/3DDFA#87]
![image](https://user-images.githubusercontent.com/41495567/64316827-e99d1f80-cff0-11e9-9f16-15e4825b028a.png)

**Comment by cleardusk** [comment]
#88

**Comment by cleardusk** [comment]
Please see [rendering_demo.py](https://github.com/cleardusk/3DDFA/blob/master/demo%40obama/rendering_demo.py) for details.

**Comment by guiweit** [comment]
Thanks very much for your kind reply!!!
