### ISSUE TITLE
obama@demo

### ISSUE THREAD

**Issue by Asiyeh-Bahaloo** [cleardusk/3DDFA#88]
Hello
This is a great work and thank you for sharing your code. But i have some problem understanding it. 
There is a frame rendered with 3D model in obama@demo file. I looked in the code but there is no documentation on how u did this. I know how to calculate R,T and the 3DMM model but how can i render this 3DMM on face? how should i align 3DMM and face?
I appreciate if you explain it theoretically or just mention the code.

Thank you

**Comment by cleardusk** [comment]
I'm quite busy these days, but I may give a code demo or an explanation soon.

**Comment by Asiyeh-Bahaloo** [comment]
Thank you very much

**Comment by cleardusk** [comment]
Please see [rendering_demo.py](https://github.com/cleardusk/3DDFA/blob/master/demo%40obama/rendering_demo.py) for details.

**Comment by Asiyeh-Bahaloo** [comment]
Thank you very much for your code.  But my problem is how to use R,T. I mean The model we have is a frontal view of face which has R,T = 0 , But obama's face have some rotation and translation. So for aligning this two we just need to rotate and translate the 3D model of face, which needs ( as far as i know) triangulation , world coordinate origin and etc. I cant find the code for this part.
Thank you again

**Comment by cleardusk** [comment]
What do you mean aligning?

**Comment by Asiyeh-Bahaloo** [comment]
I want to align (Superimpose) the 3D model which is in origin of the world with obama'c face which is in some R,T. So i need to move and rotate this 3D model so it can lay on obama's face.
Am i right? or the 3D model is already have some rotation and translation?

**Comment by cleardusk** [comment]
You may refer to similarity transform or ICP, registration.

**Comment by Asiyeh-Bahaloo** [comment]
I thought you used something like projection matrix.
