### ISSUE TITLE
Questions about runtime

### ISSUE THREAD

**Issue by bleakie** [cleardusk/3DDFA#90]
why i test ：input = transform(img).unsqueeze(0).cuda() are 50ms with gtx1080ti?

**Comment by cleardusk** [comment]
Plz give the detailed code snippet of benchmark

**Comment by cleardusk** [comment]
No reply

**Comment by bleakie** [comment]
img = cv2.resize(img, dsize=(STD_SIZE, STD_SIZE), interpolation=cv2.INTER_LINEAR)
input = transform(img).unsqueeze(0)
In main.py, my test time is 50ms.

**Comment by cleardusk** [comment]
My test is 250 µs, can not reproduce your result.

**Comment by bleakie** [comment]
Very strange！！！
