### ISSUE TITLE
problem for training

### ISSUE THREAD

**Issue by jiajiajun** [cleardusk/3DDFA#92]
Thanks very much for sharing your work! But when I'm training as the readme introduces, I meet problems below, hope you can help, thank you!(python3.6.1, torch1.2.0)
do: 
python train.py
problem:
.......
[2019-09-17 14:34:44,364] [p43415] [train.py:210] [INFO] Use VDC Loss
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main()
  File "train.py", line 241, in main
    transform=transforms.Compose([ToTensorGjz(), normalize])
  File "/home/zhanglijun/FaceLandmarks/3DDFA/utils/ddfa.py", line 117, in __init__
    self.lines = Path(filelists).read_text().strip().split('\n')
  File "/usr/local/python3.6.1/lib/python3.6/pathlib.py", line 1177, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/python3.6.1/lib/python3.6/pathlib.py", line 1164, in open
    opener=self._opener)
IsADirectoryError: [Errno 21] Is a directory: '.'

**Comment by cleardusk** [comment]
Make sure the path contains the file. It is obviously the path problem.

**Comment by jiajiajun** [comment]
Thanks for your reply! I'm sure the path in bash scripts is right and contains the file. Is there any other paths I've missed?

LOG_ALIAS=$1
LOG_DIR="logs"
mkdir -p ${LOG_DIR}

LOG_FILE="${LOG_DIR}/${LOG_ALIAS}_`date +'%Y-%m-%d_%H:%M.%S'`.log"
#echo $LOG_FILE

./train.py --arch="mobilenet_1" \
    --start-epoch=1 \
    --loss=wpdc \
    --snapshot="snapshot/phase1_wpdc" \
    --param-fp-train='/home/XXX/3DDFA/train.configs/param_all_norm.pkl' \
    --param-fp-val='/home/XXX/3DDFA/train.configs/param_all_norm_val.pkl' \
    --warmup=5 \
    --opt-style=resample \
    --resample-num=132 \
    --batch-size=512 \
    --base-lr=0.02 \
    --epochs=50 \
    --milestones=30,40 \
    --print-freq=50 \
    --devices-id=0,1 \
    --workers=8 \
    --filelists-train="/home/XXX/3DDFA/train.configs/train_aug_120x120.list.train" \
    --filelists-val="/home/XXX/3DDFA/train.configs/train_aug_120x120.list.val" \
    --root="/home/XXX/3DDFA/train_aug_120x120" \
    --log-file="${LOG_FILE}"

**Comment by cleardusk** [comment]
I suggest you may debug it first. Jump to here `File "/home/zhanglijun/FaceLandmarks/3DDFA/utils/ddfa.py", line 117`

**Comment by jiajiajun** [comment]
Thanks for your help, I've solved the problem.

**Comment by cleardusk** [comment]
Ok.

**Comment by gd1925** [comment]
Hi @jiajiajun, I am facing the same issue. my filelists is empty. 
How did you solve the issue? Could you help me too?
