### ISSUE TITLE
3D  Annotations of 300W-LP

### ISSUE THREAD

**Issue by Gnabe** [cleardusk/3DDFA#94]
Hi,
I am trying to train my face alignment network on 300W-LP only. Is there a way to get the Ground Truth annotations of the 300W-LP dataset, meaning only the 63000 pictures as opposed to more than 600000? Since I dont want to use the Basel Face Model i would love to leave the fitting error out of the ground truth. Any help would be appreciated.
Thank you

**Comment by cleardusk** [comment]
see http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm

**Comment by Gnabe** [comment]
thanks for the response. If I want to obtain the 3D coordinates, i need to construct the vertices using the model used in the paper right? Is there any code for that since it is a different amount of parameters (different model?)
thanks

**Comment by cleardusk** [comment]
It seems that you are new to this field. I suggest you go through http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm in detail. Or you may refer to face3d: https://github.com/YadiraF/face3d.
