### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'samples/246.jpg.bbox'

### ISSUE THREAD

**Issue by gudianyue** [cleardusk/3DDFA#96]
一开始执行：python3 main.py -f samples/274.jpg
结果可以顺利运行:
Dump tp samples/274_0.ply
Save 68 3d landmarks to samples/274_0.txt
Dump obj with sampled texture to samples/274_0.obj
Dump to samples/274_pose.jpg
Dump to samples/274_depth.png
Dump to samples/274_pncc.png
Save visualization result to samples/274_3DDFA.jpg
但是当第三次运行的时候（第三张差不多格式的图片）：
python3 main.py -f samples/246.jpg
结果出错
Traceback (most recent call last):
  File "main.py", line 205, in <module>
    main(args)
  File "main.py", line 71, in main
    lines = open(rect_fp).read().strip().split('\n')[1:]
FileNotFoundError: [Errno 2] No such file or directory: 'samples/246.jpg.bbox'

**Comment by cleardusk** [comment]
这种情况应该是你的 247.jpg 没有检测到人脸（dlib 检测比较弱）；你可以换个检测器或者用上一帧的关键点/框来初始化 247 帧。
