### ISSUE TITLE
关于remove neck版本的BFM模型

### ISSUE THREAD

**Issue by codediner** [cleardusk/3DDFA#98]
嗨，您好，
  
      非常感谢3DDFA的开源。

      有一个问题需要咨询一下您，您开源了BFM的remove neck的model_refine.mat,我想知道如何用mdoel_refine.mat在inference中得到去掉脖子的实时的3D人脸模型？这个model_refine.mat应该不需要在训练中加载吧？

**Comment by cleardusk** [comment]
您好：这个版本的模型暂时并未提供。你可以用 meshlab 等软件手动去掉脖子，更新面片索引。

**Comment by codediner** [comment]
好的，谢谢
