### ISSUE TITLE
Questions about rending 

### ISSUE THREAD

**Issue by guiweit** [cleardusk/3DDFA#99]
Thanks very much for your great job and kind sharing!

I have a question about colors of rending,  while I reconstructing and rendering a face with the data(vertices, triangles, colors, image), I can not change the color same to original one. for details please reference to the attached picture.

I am expecting to get your kind helps and some useful advice.
![photo_fit](https://user-images.githubusercontent.com/41495567/65845992-27cefa00-e377-11e9-84a4-a176ec81b513.png)

**Comment by cleardusk** [comment]
Plz follow the demos.

**Comment by guiweit** [comment]
Thanks very much for your reply!
